export interface LoaderIngredient {
  emoji: string;
  name: string;
}

export const COOKING_LOADER_INGREDIENTS: LoaderIngredient[] = [
  { emoji: '🥔', name: 'Papa' },
  { emoji: '🧅', name: 'Cebolla' },
  { emoji: '🍅', name: 'Tomate' },
  { emoji: '🥕', name: 'Zanahoria' },
  { emoji: '🌽', name: 'Choclo' },
  { emoji: '🍋', name: 'Limón' },
  { emoji: '🧄', name: 'Ajo' },
  { emoji: '🌶️', name: 'Morrón' },
  { emoji: '🥩', name: 'Carne' },
  { emoji: '🍗', name: 'Pollo' },
  { emoji: '🐟', name: 'Pescado' },
  { emoji: '🥚', name: 'Huevo' },
  { emoji: '🧀', name: 'Queso' },
  { emoji: '🫘', name: 'Porotos' },
  { emoji: '🍚', name: 'Arroz' },
  { emoji: '🍝', name: 'Fideos' },
  { emoji: '🥬', name: 'Lechuga' },
  { emoji: '🥑', name: 'Palta' },
  { emoji: '🍄', name: 'Champiñón' },
  { emoji: '🫑', name: 'Morrón verde' },
  { emoji: '🥒', name: 'Pepino' },
  { emoji: '🍠', name: 'Batata' },
  { emoji: '🧈', name: 'Manteca' },
  { emoji: '🫒', name: 'Aceitunas' },
  { emoji: '🌿', name: 'Albahaca' },
  { emoji: '🍖', name: 'Asado' },
  { emoji: '🥖', name: 'Pan' },
  { emoji: '🍤', name: 'Camarones' },
  { emoji: '🥛', name: 'Leche' },
  { emoji: '🍯', name: 'Miel' },
];

/** Frases rotativas del loader — tono cocina casera / rioplatense. */
export const COOKING_LOADER_PHRASES: string[] = [
  'Revisando recetas de cocina…',
  'Buscando en el libro de la abuela…',
  'Pelando papas…',
  'Cortando cebolla sin llorar…',
  'Revolvemos la olla…',
  'Probando si le falta sal…',
  'Preguntándole al mate qué cocinar…',
  'Abriendo la heladera mentalmente…',
  'Calentando el aceite…',
  'Dorando el ajo en la sartén…',
  'Haciendo un sofrito de base…',
  'Buscando la sartén grande…',
  'Revisando qué hay en la alacena…',
  'Consultando con la nona…',
  'Hojeando recetas manchadas de salsa…',
  'Cortando morrones en juliana…',
  'Lavando la verdura…',
  'Sacando la carne del freezer…',
  'Marinando un poquito…',
  'Buscando el mortero de especias…',
  'Olfateando el comino…',
  'Rallando queso…',
  'Batendo huevos…',
  'Amasando con paciencia…',
  'Precalentando el horno…',
  'Enmantecando la fuente…',
  'Buscando la tapa que cierra bien…',
  'Reviviendo recetas de la infancia…',
  'Pensando en un toque de limón…',
  'Viendo si entra en la olla…',
  'Cortando en cubitos…',
  'Picando perejil fresquito…',
  'Tostando semillas…',
  'Reduciendo la salsa…',
  'Dejando reposar la masa…',
  'Buscando la receta del cuaderno…',
  'Preguntando "¿y si le ponemos queso?"…',
  'Calculando cuánta sal "a ojo"…',
  'Revisando el tiempo de cocción…',
  'Girando la sartén con estilo…',
  'Buscando la espátula de madera…',
  'Probando la mezcla con la cucharita…',
  'Haciendo espacio en la mesada…',
  'Sacudiendo harina del delantal…',
  'Buscando un plato bien presentable…',
  'Inventando con lo que hay…',
  'Mezclando sabores que combinen…',
  'Evitando que se pegue al fondo…',
  'Tapando la olla a fuego bajo…',
  'Destapando para ver si ya está…',
  'Agregando un toque de hierbas…',
  'Fileteando finito…',
  'Cocinando a fuego lento…',
  'Dándole amor al plato…',
  'Casi listo, aguantá un toque…',
  'Armando algo rico para vos…',
  'Buscando la combinación perfecta…',
  'Revisando la lista del mercado…',
  'Imaginando el aroma en la cocina…',
  'Probando si queda bien con arroz…',
  'Viendo si conviene al horno…',
  'Preparando la mesa en la cabeza…',
  'Sacando ideas del recetario mental…',
  'Consultando al chef interior…',
  'Ajustando las porciones…',
  'Buscando el equilibrio justo…',
  'Pelando choclo con cuidado…',
  'Cortando zapallito en rodajas…',
  'Reviviendo el sabor de casa…',
  'Haciendo magia con ingredientes simples…',
];
