-- AI generation observability. Apply before setting AI_OBSERVABILITY_PERSISTENCE=true.

CREATE TABLE IF NOT EXISTS ai_model_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  input_usd_per_million NUMERIC(18, 9) NOT NULL,
  output_usd_per_million NUMERIC(18, 9) NOT NULL,
  cached_input_usd_per_million NUMERIC(18, 9),
  reasoning_usd_per_million NUMERIC(18, 9),
  request_usd NUMERIC(18, 9),
  valid_from TIMESTAMPTZ NOT NULL,
  valid_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ai_model_prices_valid_range CHECK (valid_until IS NULL OR valid_until > valid_from),
  CONSTRAINT ai_model_prices_unique_start UNIQUE (provider, model, valid_from)
);

CREATE INDEX IF NOT EXISTS idx_ai_model_prices_lookup
  ON ai_model_prices (provider, model, valid_from DESC);

CREATE TABLE IF NOT EXISTS ai_generations (
  id UUID PRIMARY KEY,
  request_id UUID NOT NULL,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  operation TEXT NOT NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  recipe JSONB NOT NULL,
  schema_version SMALLINT NOT NULL DEFAULT 1,
  status TEXT NOT NULL CHECK (status IN ('completed', 'failed')),
  input_tokens INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  total_tokens INTEGER NOT NULL DEFAULT 0,
  usage_estimated BOOLEAN NOT NULL DEFAULT false,
  usage_lines JSONB NOT NULL DEFAULT '[]'::jsonb,
  total_cost_usd NUMERIC(18, 9),
  retry_count INTEGER NOT NULL DEFAULT 0,
  started_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ NOT NULL,
  total_duration_ms NUMERIC(14, 2) NOT NULL,
  error_category TEXT,
  error_code TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_generations_started
  ON ai_generations (started_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_generations_user_started
  ON ai_generations (user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_generations_model_started
  ON ai_generations (provider, model, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_generations_status_started
  ON ai_generations (status, started_at DESC);

CREATE TABLE IF NOT EXISTS ai_generation_stages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  generation_id UUID NOT NULL REFERENCES ai_generations(id) ON DELETE CASCADE,
  sequence SMALLINT NOT NULL,
  stage TEXT NOT NULL,
  duration_ms NUMERIC(14, 2) NOT NULL,
  success BOOLEAN NOT NULL,
  attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_category TEXT,
  error_code TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ai_generation_stages_unique_sequence UNIQUE (generation_id, sequence)
);

CREATE INDEX IF NOT EXISTS idx_ai_generation_stages_stage
  ON ai_generation_stages (stage, created_at DESC);

CREATE TABLE IF NOT EXISTS ai_provider_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  generation_id UUID NOT NULL REFERENCES ai_generations(id) ON DELETE CASCADE,
  attempt SMALLINT NOT NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  duration_ms NUMERIC(14, 2) NOT NULL,
  success BOOLEAN NOT NULL,
  usage JSONB NOT NULL DEFAULT '{}'::jsonb,
  finish_reason TEXT,
  error_category TEXT,
  error_code TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ai_provider_attempts_unique_attempt UNIQUE (generation_id, attempt)
);

CREATE INDEX IF NOT EXISTS idx_ai_provider_attempts_model
  ON ai_provider_attempts (provider, model, created_at DESC);

CREATE TABLE IF NOT EXISTS ai_quality_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  generation_id UUID NOT NULL REFERENCES ai_generations(id) ON DELETE CASCADE,
  metric_name TEXT NOT NULL,
  boolean_value BOOLEAN,
  numeric_value NUMERIC,
  text_value TEXT,
  status TEXT CHECK (status IS NULL OR status IN ('pass', 'fail', 'unknown')),
  expected_value TEXT,
  actual_value TEXT,
  unit TEXT,
  evaluator TEXT NOT NULL,
  evaluator_version TEXT NOT NULL,
  source TEXT NOT NULL CHECK (source IN ('server', 'client', 'human', 'llm_judge')),
  threshold_version TEXT,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ai_quality_metrics_one_value CHECK (
    (boolean_value IS NOT NULL)::INTEGER
    + (numeric_value IS NOT NULL)::INTEGER
    + (text_value IS NOT NULL)::INTEGER = 1
  )
);

CREATE INDEX IF NOT EXISTS idx_ai_quality_metrics_name_created
  ON ai_quality_metrics (metric_name, created_at DESC);

CREATE TABLE IF NOT EXISTS ai_generation_payloads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  generation_id UUID NOT NULL REFERENCES ai_generations(id) ON DELETE CASCADE,
  payload_type TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  encrypted_content TEXT,
  redaction_version TEXT NOT NULL,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_generation_payloads_expiry
  ON ai_generation_payloads (expires_at)
  WHERE expires_at IS NOT NULL;

ALTER TABLE ai_model_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_generations ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_generation_stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_provider_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_quality_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_generation_payloads ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE VIEW ai_generation_daily_metrics AS
SELECT
  date_trunc('day', started_at) AS day,
  operation,
  provider,
  model,
  count(*) AS requests,
  count(*) FILTER (WHERE status = 'failed') AS errors,
  avg(total_duration_ms) AS average_duration_ms,
  percentile_cont(0.95) WITHIN GROUP (ORDER BY total_duration_ms) AS p95_duration_ms,
  percentile_cont(0.99) WITHIN GROUP (ORDER BY total_duration_ms) AS p99_duration_ms,
  avg(total_tokens) AS average_tokens,
  sum(total_tokens) AS total_tokens,
  avg(total_cost_usd) AS average_cost_usd,
  sum(total_cost_usd) AS total_cost_usd,
  avg(retry_count) AS average_retries
FROM ai_generations
GROUP BY 1, 2, 3, 4;

CREATE OR REPLACE VIEW ai_stage_daily_metrics AS
SELECT
  date_trunc('day', stage.created_at) AS day,
  generation.operation,
  generation.provider,
  generation.model,
  stage.stage,
  count(*) AS executions,
  avg(stage.duration_ms) AS average_duration_ms,
  percentile_cont(0.95) WITHIN GROUP (ORDER BY stage.duration_ms) AS p95_duration_ms,
  percentile_cont(0.99) WITHIN GROUP (ORDER BY stage.duration_ms) AS p99_duration_ms,
  count(*) FILTER (WHERE NOT stage.success) AS errors
FROM ai_generation_stages stage
JOIN ai_generations generation ON generation.id = stage.generation_id
GROUP BY 1, 2, 3, 4, 5;

-- Views do not inherit table RLS on every supported PostgreSQL version.
REVOKE ALL ON ai_generation_daily_metrics, ai_stage_daily_metrics FROM anon, authenticated;
GRANT SELECT ON ai_generation_daily_metrics, ai_stage_daily_metrics TO service_role;
